CONNECT SYSTEM/dba
DROP USER LEE CASCADE;

ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY/MM/DD';

CREATE USER LEE IDENTIFIED BY BOB
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;

GRANT CONNECT,RESOURCE,UNLIMITED TABLESPACE TO LEE;

